version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./local/mongo.yml
        target: /etc/mongod.conf
      - type: volume
        source: mongo_volume
        target: /data/db
      - type: bind
        source: ./local/mongo-init.sh
        target: /docker-entrypoint-initdb.d/mongo-init.sh
      - type: bind
        source: ./data
        target: /data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
    command: --config /etc/mongod.conf

volumes:
  mongo_volume:
